// This file is generated by Sapper — do not edit it!
export const timestamp = 1527111274957;

export const assets = [
	"favicon.png",
	"global.css",
	"manifest.json",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"client/9e9f2f78ead2a363f283/vendors~feeds_$slug$.0.js",
	"client/9e9f2f78ead2a363f283/feeds_$slug$.1.js",
	"client/9e9f2f78ead2a363f283/_.2.js",
	"client/9e9f2f78ead2a363f283/_5xx.3.js",
	"client/9e9f2f78ead2a363f283/_4xx.4.js",
	"client/9e9f2f78ead2a363f283/main.js"
];

export const routes = [
	
];